-- Database for the recipe app. Paste all of this into Supabase > SQL Editor and
-- click Run, once, on a new project. It holds no recipes (those come from
-- dev/import.sql, which is never committed), so this file is safe to publish.

-- ---------- recipes ----------

create table public.recipes (
  -- "by default" so the import can give each sheet row its own number in the
  -- original order. The app shows the highest id first, so newest first.
  id bigint generated by default as identity primary key,

  -- Her values were typed by hand ("To try", "Main course ", blank cells) and
  -- are kept exactly as written, so there are no CHECK constraints here. The
  -- app reads them forgivingly and writes the tidy values for new changes.
  -- Empty text is '' rather than null, the way the sheet had it.
  name     text not null default '',
  category text not null default '',
  status   text not null default '',
  link     text not null,
  -- The link in a comparable form ("yt:<video id>", "ig:<post id>", ...),
  -- worked out by linkKey() in app/links.js, used to spot the same video saved
  -- twice. Not unique: her sheet already has a few repeats.
  link_key text not null default '',
  source   text not null default '',
  notes    text not null default '',

  -- For features that are on the way; nothing uses them yet.
  protein     text,
  ingredients text[],

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index recipes_link_key_idx on public.recipes (link_key);

create function public.set_updated_at() returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger recipes_set_updated_at
  before update on public.recipes
  for each row execute function public.set_updated_at();

-- ---------- who may use the app ----------

-- Add Mom's email and your own here (Table Editor > allowed_users > Insert row).
-- Signing in is not enough on its own: the email must also be on this list.
create table public.allowed_users (
  email text primary key
);

-- Nobody reads this table through the app; only the check below uses it.
alter table public.allowed_users enable row level security;
revoke all on public.allowed_users from anon, authenticated;

-- True when the signed-in person's email is on the list. "security definer"
-- lets it look at allowed_users, which the person can't read directly.
-- Emails are compared without caring about capital letters.
create function public.is_allowed() returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.allowed_users
    where lower(trim(email)) = lower(auth.jwt() ->> 'email')
  );
$$;

revoke execute on function public.is_allowed() from public, anon;
grant execute on function public.is_allowed() to authenticated;

-- ---------- Row Level Security ----------
-- The app's key is public (it sits in app/config.js), so these rules are what
-- actually keep her recipes private: only a signed-in person on the list can
-- see, add or change them.

alter table public.recipes enable row level security;

create policy "Allowed users can read recipes"
  on public.recipes for select to authenticated
  using ((select public.is_allowed()));

create policy "Allowed users can add recipes"
  on public.recipes for insert to authenticated
  with check ((select public.is_allowed()));

create policy "Allowed users can change recipes"
  on public.recipes for update to authenticated
  using ((select public.is_allowed()))
  with check ((select public.is_allowed()));

-- No delete rule, so nothing can be deleted through the app: "Remove" only
-- sets the status to Not Interested. Removing the permission as well makes
-- that doubly sure.
revoke delete, truncate on public.recipes from anon, authenticated;
grant select, insert, update on public.recipes to authenticated;

-- Signed-out visitors may ask, but the rules above give them no rows. This is
-- what the keep-alive check (.github/workflows/keepalive.yml) relies on: it
-- gets an empty answer, which still counts as the database being used.
grant select on public.recipes to anon;
revoke insert, update on public.recipes from anon;
